# Generated by Django 4.2.16 on 2024-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Google_Authentication', '0002_googleoauthkeys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleoauthkeys',
            old_name='google_client_id',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='googleoauthkeys',
            old_name='google_client_secret',
            new_name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googleoauthkeys',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googleoauthkeys',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='googleoauthkeys',
            name='token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
