# Generated by Django 4.2.16 on 2024-11-19 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Google_Authentication', '0003_rename_google_client_id_googleoauthkeys_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauthkeys',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googleoauthkeys',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleoauthkeys',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleoauthkeys',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
